// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxfjxmxchohqnzafdmej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4Zmp4bXhjaG9ocW56YWZkbWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNjQ5MzAsImV4cCI6MjA3MjY0MDkzMH0.YmPcvQEDVr7nWA3MtRGS562rNlT32rQp7vghQGX52Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});